In [3]:

import numpy as np
import csv

In [11]:
with open('AAPL-2017.csv', newline = '') as a:
    reader = csv.DictReader(a)
    stock2017 = np.empty((0, 6))
    for row in reader:
        oneRow = np.array([[row['Open'], row['High'], row['Low'],row['Close'],row['Adj Close'], row['Volume']]])
        stock2017 = np.append(stock2017,oneRow, axis=0)
print(stock2017.astype('float64'))

[[ 115.80  116.33  114.76  116.15  113.01  28781900.00]
 [ 115.85  116.51  115.75  116.02  112.89  21118100.00]
 [ 115.92  116.86  115.81  116.61  113.46  22193600.00]
 ...
 [ 170.10  170.78  169.71  170.60  168.66  21498200.00]
 [ 171.00  171.85  170.48  171.08  169.14  16480200.00]
 [ 170.52  170.59  169.22  169.23  167.31  25884400.00]]


In [8]:
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})